### ISSUE TITLE
say hi

### ISSUE THREAD

**Issue by gaoyoubo** [Xonlystar/hexo-blog-client#1]
hi，看到你的工程是基于：https://github.com/gaoyoubo/hexo-client  这里修改的。我是原hexo-client的作者，我本身并非专业前端开发，我也是出于需求出发，边学习边完善功能的。能否邀请你一起加入到hexo-client的开发，一起努力将hexo-client完善。

**Comment by Xonlystar** [comment]
有很久没有使用hexo博客了，后来一直用有道云笔记，今天才看到这个，抱歉。
