### ISSUE TITLE
选择路径后没进入控制界面

### ISSUE THREAD

**Issue by fmkli** [Xonlystar/hexo-blog-client#11]
选择hexo安装路径后无反应

**Comment by maojunhat** [comment]
一样的问题，显示一瞬间的加载图标之后就没反应了

**Comment by ezrameek** [comment]
> 选择hexo安装路径后无反应

我也是，请问解决了吗

**Comment by fmkli** [comment]
> > 选择hexo安装路径后无反应
> 
> 我也是，请问解决了吗

很早就没用过了，最后一个 releases 是在 2019 年了，换个东西试试吧
