### ISSUE TITLE
初始化界面【请先填写正确的Hexo安装目录】，只允许dialog选择无法完成设置

### ISSUE THREAD

**Issue by webooxx** [Xonlystar/hexo-blog-client#2]
我的hexo是全局安装的，路径在

> /usr/local/bin/hexo

使用对话框的形式无法完成选择，mac的 finder 无法选择到根目录

![20190625105739](https://user-images.githubusercontent.com/668454/60065959-2d91bf80-9738-11e9-96ea-cab8392e7bae.jpg)

**Comment by Xonlystar** [comment]
这个问题我将在下一版本中添加`手动输入路径`的方式
目前使用的话可以如下操作：
- 在mac终端打开配置文件 `open ~/.hexo-blog-client/sysConfig.json`，没有该文件需自行创建
- 配置里面的`path`，添加你hexo博客的路径

sysConfig.json默认配置如下
```json
{
	"path": "",
	"base": "",
	"url": "",
	"language": "zh",
	"uploadType": "github",
	"qiniuZone": "",
	"qiniuAccessKey": "",
	"qiniuSecretKey": "",
	"qiniuBucket": "",
	"qiniuHost": "",
	"autoUpdate": false
}

```

**Comment by B14070315** [comment]
mac 打开直接白屏，是我姿势有问题吗？
![image](https://user-images.githubusercontent.com/16371746/60099773-f13b7f00-978a-11e9-9c7a-efe76202a38d.png)

**Comment by B14070315** [comment]
刚才重新下载dmg文件试了几次，还是一样的问题，检查更新貌似是可以的，但是每次一启动就白屏，也没有可以看日志的地方，建议将启动日志打印出来，方便定位问题
![image](https://user-images.githubusercontent.com/16371746/60101497-72e0dc00-978e-11e9-9a33-c3fed406bdbd.png)
通过终端启动，倒是可以看到一点日志，希望对你定位问题有帮助
![image](https://user-images.githubusercontent.com/16371746/60101571-9441c800-978e-11e9-9b0e-0817db080804.png)
顺便问下最近还有更新吗？我是通过gitlab部署的hexo，其它的hexo客户端貌似支持的不够好，精力有限，就不自己造轮子了，这个客户端希望能一直维护下去 @Xonlystar

**Comment by Xonlystar** [comment]
我用的也是gitlab部署的hexo啊，在mac下也用了这么久没有发现问题的。
你这个问题我这这两天会找找原因，尽快解决

**Comment by Xonlystar** [comment]
放心吧，这个客户端我会一直迭代下去，不出意外的话，我解决掉问题后，7月份会再发一个版本。
