### ISSUE TITLE
修改路径后重启打开报错，重装也是一样

### ISSUE THREAD

**Issue by hujiejeff** [Xonlystar/hexo-blog-client#3]
![image](https://user-images.githubusercontent.com/22571708/60417010-deed9500-9c11-11e9-8b00-24ce735ca218.png)

**Comment by Xonlystar** [comment]
那应该是你的hexo博客的路径有问题，你找到下面的文件删掉，再重新打开软件
`C:\用户\当前用户名\AppData`
目录下找隐藏文件  `.hexob-blog-client`

![image](https://user-images.githubusercontent.com/19361551/60418375-57a22080-9c15-11e9-9a33-18445600866f.png)
