### ISSUE TITLE
发布失败

### ISSUE THREAD

**Issue by zaizizaizai** [Xonlystar/hexo-blog-client#4]
发布失败，且不能打开博客

**Comment by onlyxhb** [comment]
发布博客有两种方式
第一种是配置ssh，提交到git仓库，然后仓库执行ci/cd持续继承。具体请参https://blog.onlystar.site/2018/10/21/hexoblogclient-shi-yong-zhi-nan/

第二种就是hexo自带的的hexo deploy，这种方式需要在设置里配置，然后提交就行了

**Comment by onlyxhb** [comment]
你这边具体是怎么操作的呢？博客不能打开，是本地的还是线上的？

**Comment by zaizizaizai** [comment]
客户端有两个功能使用不了，我的博客（链接图标），上传失败，我的博客是放在github.io上的

**Comment by onlyxhb** [comment]
打开 `设置` -> `打开开发者工具`,看看控制台有没有报错，把错误信息贴出来看看
